### ISSUE TITLE
Cannot activate on staging after cloning

### ISSUE THREAD

**Issue by plermant** [akamai-open/akamaiconfigkit-public#3]
Error when trying to push to staging the new config after cloning from template. Note that the Luna UI shows no error for the configuration (only warnings) however when I try to activate it says there are errors, both thru the UI and thru your api. 
Will have to be fixed for GA
 
plermant@ubuntu:/mnt/hgfs/Customers/Macys/APIs/akamaiconfigkit-public/bin$ akamaiProperty activate dev2 --network STAG --email plermant@akamai.com
Activating dev2 on STAG
Init PropertyManager cache (hostnames and property list)
... retrieving list of Group Ids
... retrieving properties from 16 groups
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24705}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63900}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_63903}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24708}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24707}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24703}
... no permissions, ignoring  {ctr_3-1AZ95HC : grp_54598}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64635}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24710}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_54598}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_48393}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_101295}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_64634}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_24709}
... no permissions, ignoring  {ctr_1-1U72M7 : grp_82575}
... retrieving Hosts from 3 properties
Init PropertyManager cache: 5651.305ms
Activating dev2 to STAGING
... activating property (dev2) v2
... activating: 402.487ms
ERROR:  {"type":"https://problems.luna.akamaiapis.net/papi/v0/activation/errors","status":400,"instance":"https://akab-wtvypdbx5afxmj5v-ot3mzadys7hcnfsx.luna.akamaiapis.net/papi/v0/properties/prp_375053/activations?contractId=ctr_1-1U72M7&groupId=grp_101490#0ad406d0-4650-43bf-b8a7-ae6afc669939","warnings":[{"type":"https://problems.luna.akamaiapis.net/papi/v0/activation/unstable_rule_format","detail":"This property is using `latest` rule format, which is designed to reflect interface changes immediately. We suggest converting the property to a stable rule format such as `v2016-11-15` to minimize the risk of interface changes breaking your API client program.","messageId":"msg_eac797d55da505d7f40dcd3857d003c83ba8d7c1"}],"errors":[{"type":"https://problems.luna.akamaiapis.net/papi/v0/activation/validation_errors_exist","detail":"There are validation errors that exist. Please return to the edit page to correct them.","messageId":"msg_48d270436925422781ac6dd06763470987ed7a5d

**Comment by synedra** [comment]
This has been opened as a case for the engineering team, closing it here as it's not a tool issue.
