### ISSUE TITLE
Ability to modify user variables thru the Create function

### ISSUE THREAD

**Issue by plermant** [akamai-open/akamaiconfigkit-public#4]
Add a new parameter to the ‘create’ function called userVariables that would take a json structure as input as follows: [{param1:{initial:value,desc:value,security:value}},{param2:{initial:value,desc:value,security:value}},{param3 …}] and behavior would be: if paramX exists in the source ruleset as a PM_USER variable it would update its value in the destination config. If it does not exist it would be ignored. Note that the "security" key can only take one of three predefined value (Visible,Hidden or Sensitive), and the "initial" key has also some character requirements (e.g. no white space)

**Comment by plermant** [comment]
Regarding the security parameter of the user variable, since it’s one of only 3 possible values, can we make it simpler, and instead of specifying “hidden” = false, “sensitive=false, can’t we instead have one key called “security” that can only take one of 3 values (hidden/sensitive/visible), with default being ‘visible’. This would also alleviate possible complex default logic, if say for instance both ‘hidden’ and ‘sensitive’ were set to ‘true’ at the same time

**Comment by synedra** [comment]
This is done with modify.
