### ISSUE TITLE
Ability to modify the Forward Host Header param thru the Create command

### ISSUE THREAD

**Issue by plermant** [akamai-open/akamaiconfigkit-public#5]
Suggested implementation:
Add a parameter to the ‘create’ function called forwardHostHeader that could take one of 3 values:
a.	_originhostname: It would set the UI param “forward host header” to the predefined Origin Hostname
b.	_incominghostheader: it would set the UI param “forward host header” to predefined  Incoming Host Header.
c.	Any other string: it would set the UI param ”forward host header” to “custom value” and set the UI parameter Custom Forward Host Header to the incoming string

**Comment by synedra** [comment]
This is done.
