### ISSUE TITLE
Trying to delete an activated property fails: akamaiProperty delete someConfig

### ISSUE THREAD

**Issue by plermant** [akamai-open/akamaiconfigkit-public#7]
Per Luna UI, when a property has been activated in staging or production, it needs to be deactivated before it can be deleted. Now we get an error message: e.g.:
... deleting property: 282.361ms
ERROR:  {"type":"https://problems.luna.akamaiapis.net/papi/v0/toolkit/cant_delete_property","instance":"https://akab-wtvypdbx5afxmj5v-ot3mzadys7hcnfsx.luna.akamaiapis.net/papi/v0/properties/prp_375396?contractId=ctr_1-1U72M7&groupId=grp_101490#ae50ef8a-48fe-456c-ad6b-2b891c415002"}

**Comment by synedra** [comment]
Delete now deactivates first.
