### ISSUE TITLE
Specifying version number "create --srcver versionNumber" throws an error

### ISSUE THREAD

**Issue by plermant** [akamai-open/akamaiconfigkit-public#9]
I am wrapping the configKit with python, like:
result=subprocess.check_output(req)
with for instance 
req=("['akamaiProperty', 'create', 'dev22', '--clone', 'template.com', '--srcver', '2', '--forward', 'tryThis.com', '--origin', 'pierreOrigin.com']")
Note that I have to set the srcver to a string else subprocess will fail.
configKit throws following error:
(node:31127) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Unable to parse version string

Note that it seems to also fails in the native cli command ...

Can this be addressed?

**Comment by synedra** [comment]
This has been fixed.
